In [1]:
import numpy as np
import sklearn
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
y_train = df_train['Survived']
x_train = df_train.drop('Survived',axis = 1)
x_test = df_test
x_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [4]:
#data cleaning
x_train = x_train.drop('PassengerId',axis=1)
x_test = x_test.drop('PassengerId',axis=1)

In [5]:
x_train = x_train.drop('Name',axis=1)
x_test = x_test.drop('Name',axis=1)

In [6]:
x_train = x_train.drop('Cabin',axis=1)
x_test = x_test.drop('Cabin',axis=1)

In [7]:
x_train = x_train.drop('Ticket',axis=1)
x_test = x_test.drop('Ticket',axis=1)

In [8]:
x_train.isnull().sum()

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [9]:
x_train['Sex']=pd.get_dummies(x_train['Sex'],drop_first=True)
x_train.head()

Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0       3    1  22.0      1      0   7.2500        S
1       1    0  38.0      1      0  71.2833        C
2       3    0  26.0      0      0   7.9250        S
3       1    0  35.0      1      0  53.1000        S
4       3    1  35.0      0      0   8.0500        S

In [10]:
x_test['Sex']=pd.get_dummies(x_test['Sex'],drop_first=True)
x_test.head()

Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0       3    1  34.5      0      0   7.8292        Q
1       3    0  47.0      1      0   7.0000        S
2       2    1  62.0      0      0   9.6875        Q
3       3    1  27.0      0      0   8.6625        S
4       3    0  22.0      1      1  12.2875        S

In [11]:
x_train['Embarked'] = x_train['Embarked'].fillna('S')
x_train['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [12]:
x_train['Embarked']=pd.get_dummies(x_train['Embarked'],drop_first=True)
x_train.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         0
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         0
3       1    0  35.0      1      0  53.1000         0
4       3    1  35.0      0      0   8.0500         0

In [13]:
x_train['Pclass']=pd.get_dummies(x_train['Pclass'],drop_first=True)
x_train.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       0    1  22.0      1      0   7.2500         0
1       0    0  38.0      1      0  71.2833         0
2       0    0  26.0      0      0   7.9250         0
3       0    0  35.0      1      0  53.1000         0
4       0    1  35.0      0      0   8.0500         0

In [14]:
x_test['Pclass']=pd.get_dummies(x_test['Pclass'],drop_first=True)
x_test.head()

Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0       0    1  34.5      0      0   7.8292        Q
1       0    0  47.0      1      0   7.0000        S
2       1    1  62.0      0      0   9.6875        Q
3       0    1  27.0      0      0   8.6625        S
4       0    0  22.0      1      1  12.2875        S

In [15]:
x_test['Embarked']=pd.get_dummies(x_test['Embarked'],drop_first=True)
x_test.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       0    1  34.5      0      0   7.8292         1
1       0    0  47.0      1      0   7.0000         0
2       1    1  62.0      0      0   9.6875         1
3       0    1  27.0      0      0   8.6625         0
4       0    0  22.0      1      1  12.2875         0

In [16]:
x_train['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [17]:
avg_age = x_train['Age'].mean()
x_train['Age']=x_train['Age'].fillna(avg_age)
x_train['Age'][888]

29.69911764705882

In [18]:
avg_age_test = x_test['Age'].mean()
x_test['Age']=x_test['Age'].fillna(avg_age_test)

In [19]:
x_test['Fare'] = x_test['Fare'].fillna(x_test['Fare'].mean())
x_test.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       0    1  34.5      0      0   7.8292         1
1       0    0  47.0      1      0   7.0000         0
2       1    1  62.0      0      0   9.6875         1
3       0    1  27.0      0      0   8.6625         0
4       0    0  22.0      1      1  12.2875         0

In [20]:
#normalization:

In [21]:
x_test['Age'] = x_test['Age']/x_train['Age'].max()
x_train['Age'] = x_train['Age']/x_train['Age'].max()

In [22]:
x_train.head()

Pclass  Sex     Age  SibSp  Parch     Fare  Embarked
0       0    1  0.2750      1      0   7.2500         0
1       0    0  0.4750      1      0  71.2833         0
2       0    0  0.3250      0      0   7.9250         0
3       0    0  0.4375      1      0  53.1000         0
4       0    1  0.4375      0      0   8.0500         0

In [23]:
x_test.head()

Pclass  Sex      Age  SibSp  Parch     Fare  Embarked
0       0    1  0.43125      0      0   7.8292         1
1       0    0  0.58750      1      0   7.0000         0
2       1    1  0.77500      0      0   9.6875         1
3       0    1  0.33750      0      0   8.6625         0
4       0    0  0.27500      1      1  12.2875         0

In [24]:
x_test['Fare'] = x_test['Fare']/x_train['Fare'].max()
x_train['Fare'] = x_train['Fare']/x_train['Fare'].max()

In [25]:
x_train.head()

Pclass  Sex     Age  SibSp  Parch      Fare  Embarked
0       0    1  0.2750      1      0  0.014151         0
1       0    0  0.4750      1      0  0.139136         0
2       0    0  0.3250      0      0  0.015469         0
3       0    0  0.4375      1      0  0.103644         0
4       0    1  0.4375      0      0  0.015713         0

In [26]:
x_test.head()

Pclass  Sex      Age  SibSp  Parch      Fare  Embarked
0       0    1  0.43125      0      0  0.015282         1
1       0    0  0.58750      1      0  0.013663         0
2       1    1  0.77500      0      0  0.018909         1
3       0    1  0.33750      0      0  0.016908         0
4       0    0  0.27500      1      1  0.023984         0

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
clf = LogisticRegression(max_iter=1000)

In [29]:
clf.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [33]:
result = clf.predict(x_test)
result

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [31]:
check_df = pd.read_csv('gender_submission.csv')
check_arr = np.array(check_df['Survived'])
check_arr

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [32]:
result == check_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,